# Generated by Django 2.1.3 on 2018-11-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone', '0002_redditprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditprofile',
            name='icon_url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redditprofile',
            name='karma',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
