# Generated by Django 2.1.3 on 2018-11-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone', '0003_auto_20181112_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='redditprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='textpost',
            old_name='subreddit_id',
            new_name='subreddit',
        ),
        migrations.RenameField(
            model_name='textpost',
            old_name='user_id',
            new_name='user',
        ),
    ]
