# Generated by Django 2.1.3 on 2018-11-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone', '0005_auto_20181112_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textpost',
            old_name='subreddit_id',
            new_name='subreddit',
        ),
        migrations.RenameField(
            model_name='textpost',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='redditprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
